command.readTicket: "read"
command.openTicket: "open"
command.closeTicket: "close"
command.reopenTicket: "reopen"
command.claimTicket: "claim"
command.assignTicket: "assign"
command.unclaimTicket: "unclaim"
command.holdTicket: "hold"
command.teleportToTicket: "tp"
command.broadcastToStaff: "broadcast"
command.listStaff: "staff"

ticket.delay: 60
ticket.max: 5
ticket.hideOffline: false
ticket.perPage: 5
ticket.preventDuplicates: true
ticket.nag: 5
ticket.nagHeld: false
ticket.minimumWords: 3

debug: true