command:
  readTicket: "read"
  openTicket: "open"
  closeTicket: "close"
  reopenTicket: "reopen"
  claimTicket: "claim"
  assignTicket: "assign"
  unclaimTicket: "unclaim"
  holdTicket: "hold"
  teleportToTicket: "tp"
  broadcastToStaff: "broadcast"
  listStaff: "staff"

ticket:
  delay: 60
  max: 5
  hideOffline: false
  perPage: 5
  preventDuplicates: true
  nag: 5
  nagHeld: false
  minimumWords: 3

storage:
  type: mysql
  host: "127.0.0.1"
  port: 3306
  username: "username"
  password: "password"
  database: "minecraft"

general:
  hideInvisibleStaff: true
  debug: false